language: node_js
node_js:
  - '10'

addons:
  apt:
    packages:
      - xvfb

cache:
  directories:
    - node_modules
    - tests/generated_template/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

# Prevention of creating new cache archive by Travis when only some logs, source map etc. changed
before_cache:
  - rm -rf tests/generated_template/node_modules/.cache
  - rm -rf tests/generated_template/node_modules/ava/node_modules/.cache

env:
  global:
    - USE_HARD_LINKS=false # fix: Build failing with EEXIST: file already exists
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder


# Explicitly include to get some OS-specific badges
matrix:
  include:
    - name: "Linux - default template"
      os: linux
      env: TEST_SUITE=default BADGE=linux
    - name: "OSX - default template"
      os: osx
      osx_image: xcode9.4
      env: TEST_SUITE=default BADGE=osx
    - name: "Windows - default template"
      os: windows
      env: TEST_SUITE=default BADGE=windows

before_script:
  -  npm install -g vue-cli

script: bash ./tests/init.sh