language: node_js
node_js:
  - '10'

os:
  - linux
  - osx
  - windows

env:
  global:
    - USE_HARD_LINKS=false
  matrix:
    - TEST_SUITE=default
#    - TEST_SUITE=vuetify
#    - TEST_SUITE=buefy


# hack to get some OS-specific badges
matrix:
  exclude:
    - os: linux
      env: BADGE=osx
    - os: osx
      env: BADGE=linux
    - os: windows
      env: BADGE=windows

before_script:
  -  npm install -g vue-cli

script: bash ./tests/init.sh $TEST_SUITE